# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e2903e49e6d4f83a3894a334e1c2167ede6329af8b1421a7db18bb4ddee62e3017a75d5a63c0b79a3f0bcb919b24aab085731ef72686da4f5cca806b9a9ffc

test:
  secret_key_base: 30f4c41e53839804b495c5466cc3850a1be41bad9a317a303d36d837fc2cdb13b0fa74bfc3508a6e3e38fe7198772c9d6adb4e391a1b8adf5a363cc505e470e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
